### ISSUE TITLE
** (ArgumentError) incorrect padding

### ISSUE THREAD

**Issue by edthix** [techgaun/auth0_ex#10]
This error occurred when calling an Auth0Ex method for the second time.

Tested in IEX

```
Auth0Ex.Management.User.all()
{:ok, users} = Auth0Ex.Management.User.all() 

Auth0Ex.Management.User.all()
** (ArgumentError) incorrect padding
      (elixir) lib/base.ex:766: Base.do_decode64/2
    (auth0_ex) lib/auth0_ex/utils.ex:70: Auth0Ex.Utils.expired?/1
    (auth0_ex) lib/auth0_ex/utils.ex:31: Auth0Ex.Utils.get_token_from_client/0
    (auth0_ex) lib/auth0_ex/utils.ex:23: Auth0Ex.Utils.req_header/0
    (auth0_ex) lib/auth0_ex/management/user.ex:6: Auth0Ex.Management.User.do_request/4
```
I suspect need to pass in **padding: false** in [https://github.com/techgaun/auth0_ex/blob/master/lib/auth0_ex/utils.ex#L70](https://github.com/techgaun/auth0_ex/blob/master/lib/auth0_ex/utils.ex#L70)

**Comment by techgaun** [comment]
thanks @edthix for this issue. I am thinking the best thing to do for decoding JWT is to use [JOSE](https://github.com/potatosalad/erlang-jose). I will look into this in more details tomorrow.

**Comment by techgaun** [comment]
Reading the [rfc](https://tools.ietf.org/html/rfc7519#page-6), it seems that right way is to `Base.url_decode64!/2` with `padding: false` specified. I will push a fix for that

**Comment by techgaun** [comment]
@edthix could you please test the new release again? I've pushed a fix and seems to be working fine as per my tests.

**Comment by edthix** [comment]
@techgaun tested and it works now, thanks :)
