### ISSUE TITLE
Management API issues (search_engine)

### ISSUE THREAD

**Issue by LeakyBucket** [techgaun/auth0_ex#21]
According to Auth0 support they are deprecating the `v2` Search Engine.  We have run into issues were we can't retrieve all of our data using `v2` any longer.

```
Hi,

I reviewed the situation and the issue seems associated to a specific version of the search functionality. In particular, for that user I was only able to reproduce the issue when using search engine v2. The dashboard uses the latest version of the search engine when available and in your case it is and when using it I did not experienced any issues.

As mentioned in (https://auth0.com/docs/users/search/v3#migrate-from-search-engine-v2-to-v3) the v2 of the search engine is intended to be deprecated so I wanted to confirm with you if it's possible for you to already start using the v3 in your Management API calls where according to my tests you should not experience the issue?
```

I'm more than happy to add support for `v3` (I need it anyway).  However I'm curious if you would be in favor of just replacing the `v2` support with `v3` or if you would rather add a config option for `v3` and maintain the current default of `v2`?

I haven't looked too closely to see if any of the Search Engine query syntax is baked in anywhere.

**Comment by techgaun** [comment]
@LeakyBucket thanks for the information. IMO, Its best to make v3 the default and v2 as an optional configuration. Please let me know if you are gonna poke around and get the v3 stuff working. Else, I might do it next week. Thanks!

**Comment by LeakyBucket** [comment]
@techgaun I'll take a look this afternoon/first thing tomorrow morning.

**Comment by techgaun** [comment]
awesome thanks @LeakyBucket I appreciate it

**Comment by LeakyBucket** [comment]
@techgaun Opened #22 the tests fail but I'm honestly not quite sure why, looks like the env isn't setup correctly maybe?

**Comment by techgaun** [comment]
@LeakyBucket awesome thanks! looks good to me. I will look at making a new release to hex tomorrow.

The test failure might be something on setup so I will take care of that as well. Thanks for your contribution. :+1: :100:
