### ISSUE TITLE
Update LICENSE copyright holder

### ISSUE THREAD

**Issue by warmwaffles** [techgaun/auth0_ex#36]
@techgaun I think this was a small oversight but you should fill your name in and date it was created https://github.com/techgaun/auth0_ex/blob/84f6ef41a96dfb4eb5868a5e81b9bf52ffd674cf/LICENSE#L189

**Comment by techgaun** [comment]
totally thanks @warmwaffles I don't know how this happened. Thought I had used gh's license feature but maybe not. I'll fix it.

**Comment by warmwaffles** [comment]
No problem.
